# dummy comment
name: 'CD ping'
description: 'Notify the user of the dependency that a new release is available'
inputs:
  repository_name:
    description: 'The name of the repository'
    required: true
  is_composite:
    description: 'Is this a composite action repository ?'
    required: false
    default: false
  user:
    description: 'The User of this repository'
    required: true
  tag:
    description: 'The pushed tag'
    required: true
  token:
    description: 'The github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: tiawl/spaceporn-dep-action-env@v1.0.0

    - if: inputs.is_composite != 'true'
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: ${{ env.zig_version }}

    - name: Notify ${{ inputs.user }}
      env:
        DEPENDENCY: "client_payload[dependency]=${{ inputs.repository_name }}"
        ENDPOINT: "/repos/${{ github.repository_owner }}/${{ inputs.user }}/dispatches"
        EVENT_TYPE: 'event_type=ping'
        GH_TOKEN: "${{ inputs.token }}"
        IS_COMPOSITE: "${{ inputs.is_composite }}"
        TAG: "client_payload[tag]=${{ inputs.tag }}"
      shell: ${{ env.shell }}
      run: |
        hash="client_payload[hash]=$(if [[ "${IS_COMPOSITE}" != 'true' ]]; then zig fetch .; fi)"
        gh api --method POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -f "${EVENT_TYPE}" -F "${DEPENDENCY}" -F "${TAG}" -F "${hash}" \
          "${ENDPOINT}"
