name: 'CD ping'
description: 'Notify the user of the dependency that a new release is available'
inputs:
  repository_name: #${{ github.event.repository.name }}
    description: 'The name of the repository'
    required: true
  user:
    description: 'The User of this repository'
    required: true
  tag:  #GITHUB_REF_NAME
    description: 'The pushed tag'
    required: true
runs:
  using: "composite"
  steps:
    - uses: tiawl/spaceporn-dep-action-env@v1

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: ${{ env.zig_version }}

    - name: Notify ${{ inputs.user }}
      shell: ${{ env.shell }}
      run: |
        event_type='"event_type":"ping"'
        dependency="\"dependency\":\"${{ inputs.repository_name }}\""
        tag="\"tag\":\"${{ inputs.tag }}\""
        hash="\"hash\":\"$(zig fetch .)\""
        client_payload="\"client_payload\":{${dependency},${tag},${hash},}"
        json="{${event_type},${client_payload}}"
        gh api --method POST --input - \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -H 'Accept: application/vnd.github+json' \
          /repos/${GITHUB_REPOSITORY_OWNER}/${{ inputs.user }}/dispatches \
            <<< "${json}"
      env:
        GH_TOKEN: ${{ github.token }}
