name: 'ci'
description: 'Run CI test for CD ping'
inputs:
  dependency:
    description: 'The used dependency'
    required: true
  user:
    description: 'The User of this repository'
    required: true
  token:
    description: 'The github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.dependency }}"
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare CD
      id: prepare
      shell: bash
      run: |
        tags="$(git tag --points-at "$(git describe --tags --abbrev=0 2> /dev/null)" 2> /dev/null | wc -l)"
        if [[ "${tags}" == '0' ]]; then tag='0.0.0'
        elif [[ "${tags}" == '1' ]]; then tag="$(git describe --tags --abbrev=0)"; git checkout "${tag}"; fi
        printf 'tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: tiawl/spaceporn-dep-action-cd-ping@bot
      if: steps.prepare.outputs.tag != ''
      with:
        repository_name: "${{ inputs.dependency }}"
        user: "${{ inputs.user }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        token: "${{ inputs.token }}"

    - uses: actions/checkout@v4
      if: steps.prepare.outputs.tag == ''
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.user }}"

    - name: Search current tag selected by user
      id: user
      env:
        DEPENDENCY: "${{ github.repository_owner }}/${{ inputs.dependency }}"
      shell: bash
      run: |
        tag="$(grep -h -o -R "${DEPENDENCY}@v\S\+" | sed "s#^${DEPENDENCY}@##" | sort -u)"
        printf 'dep_tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: actions/checkout@v4
      if: steps.prepare.outputs.tag == ''
      with:
        repository: "${{ github.repository_owner }}/${{ inputs.dependency }}"
        ref: "${{ steps.user.outputs.dep_tag }}"

    - uses: tiawl/spaceporn-dep-action-cd-ping@bot
      if: steps.prepare.outputs.tag == ''
      with:
        repository_name: "${{ inputs.dependency }}"
        user: "${{ inputs.user }}"
        tag: "${{ steps.user.outputs.dep_tag }}"
        token: "${{ inputs.token }}"
