name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - dep: toolbox
            user: vulkan.zig
          - dep: toolbox
            user: wayland.zig
          - dep: toolbox
            user: X11.zig
          - dep: toolbox
            user: glfw.zig
          - dep: toolbox
            user: cimgui.zig
          - dep: toolbox
            user: spirv.zig
          - dep: toolbox
            user: glslang.zig
          - dep: toolbox
            user: shaderc.zig
          - dep: vulkan.zig
            user: glfw.zig
          - dep: wayland.zig
            user: glfw.zig
          - dep: X11.zig
            user: glfw.zig
          - dep: glfw.zig
            user: cimgui.zig
          - dep: cimgui.zig
            user: spaceporn
          - dep: spirv.zig
            user: shaderc.zig
          - dep: glslang.zig
            user: shaderc.zig
          - dep: shaderc.zig
            user: spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare CD
      id: prepare
      run: |
        tag="$(git describe --tags --abbrev=0)"
        git checkout "${tag}"
        printf 'tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: ./
      with:
        repository_name: "${{ matrix.repo.dep }}"
        user: "${{ matrix.repo.user }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        token: "${{ secrets.PAT }}"

  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}"
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare dump
      id: prepare
      run: |
        tag="$(git describe --tags --abbrev=0)"
        git checkout "${tag}"
        printf 'tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: ./
      with:
        repository_name: "${{ matrix.repo }}"
        user: "${{ github.event.repository.name }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        token: "${{ secrets.PAT }}"
