name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test-toolbox:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'toolbox'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-vulkan:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'vulkan.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-wayland:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'wayland.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-X11:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - glfw.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'X11.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-glfw:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - cimgui.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'glfw.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-cimgui:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'cimgui.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-spirv:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spirv.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-glslang:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'glslang.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-shaderc:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'shaderc.zig'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-env-action:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-env'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-bot-action:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-bot'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-ci-action:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-ci'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-ping-action:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn-dep-action-env
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-cd-ping'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  test-pong-action:
    permissions:
      contents: write
    strategy:
      matrix:
        user:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn
          - spaceporn-dep-action-env
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        dependency: 'spaceporn-dep-action-cd-pong'
        user: "${{ matrix.user }}"
        token: "${{ secrets.PAT }}"
    - uses: actions/checkout@v4
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - spaceporn
          - spaceporn-dep-action-env
          - spaceporn-dep-action-bot
          - spaceporn-dep-action-ci
          - spaceporn-dep-action-cd-ping
          - spaceporn-dep-action-cd-pong
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}"
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare dump
      id: prepare
      run: |
        if ! tag="$(git describe --tags --abbrev=0)"; then tag='0.0.0'
        else git checkout "${tag}"; fi
        printf 'tag=%s\n' "${tag}" >> "${GITHUB_OUTPUT}"

    - uses: tiawl/spaceporn-dep-action-cd-ping@ci
      with:
        repository_name: "${{ matrix.repo }}"
        user: "${{ github.event.repository.name }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        token: "${{ secrets.PAT }}"
