name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - user: vulkan.zig
            dep: toolbox
          - user: wayland.zig
            dep: toolbox
          - user: X11.zig
            dep: toolbox
          - user: glfw.zig
            dep: toolbox
          - user: glfw.zig
            dep: vulkan.zig
          - user: glfw.zig
            dep: wayland.zig
          - user: glfw.zig
            dep: X11.zig
          - user: cimgui.zig
            dep: toolbox
          - user: cimgui.zig
            dep: glfw.zig
          - user: spirv.zig
            dep: toolbox
          - user: glslang.zig
            dep: toolbox
          - user: shaderc.zig
            dep: toolbox
          - user: shaderc.zig
            dep: spirv.zig
          - user: shaderc.zig
            dep: glslang.zig
          - user: spaceporn
            dep: cimgui.zig
          - user: spaceporn
            dep: shaderc.zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo.dep }}"

    - name: Prepare CD
      id: prepare
      run: |
        printf 'tag=%s\n' "$(git describe --tags --abbrev=0)" >> "${GITHUB_OUTPUT}"

    - uses: tiawl/spaceporn-dep-action-cd-ping@ci
      with:
        repository_name: "${{ matrix.repo.dep }}"
        user: "${{ matrix.repo.user }}"
        tag: "${{ steps.prepare.outputs.tag }}"
        token: "${{ secrets.PAT }}"
