name: dump

on:
  repository_dispatch:
    types:
      - ping-toolbox
      - ping-vulkan.zig
      - ping-wayland.zig
      - ping-X11.zig
      - ping-glfw.zig
      - ping-cimgui.zig
      - ping-spirv.zig
      - ping-glslang.zig
      - ping-shaderc.zig
      - ping-spaceporn
      - ping-spaceporn-action-env
      - ping-spaceporn-action-bot
      - ping-spaceporn-action-ci
      - ping-spaceporn-action-cd-ping
      - ping-spaceporn-action-cd-pong

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump client_payload
        env:
          CLIENT_PAYLOAD: "${{ toJson(github.event.client_payload) }}"
        run: |
          printf '%s\n' "${CLIENT_PAYLOAD}"

      - uses: tiawl/spaceporn-action-env@1.0.1

      - name: Check client payload tag field and repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ github.event.client_payload.dependency }}"
          ref: "${{ github.event.client_payload.tag }}"

      - name: Does it needs zig ?
        id: zig
        shell: bash
        run: |
          if [[ -f "${GITHUB_WORKSPACE}/build.zig" ]]
          then
            printf 'needed=true\n' >> "${GITHUB_OUTPUT}"
          else
            printf 'needed=false\n' >> "${GITHUB_OUTPUT}"
          fi

      - uses: goto-bus-stop/setup-zig@v2.2.0
        if: steps.zig.outputs.needed == 'true'
        with:
          version: ${{ env.zig_version }}

      - name: Check client payload hash field
        env:
          PAYLOAD_HASH: "${{ github.event.client_payload.hash }}"
          URL: "${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.client_payload.dependency }}/archive/refs/tags/${{ github.event.client_payload.tag }}.tar.gz"
          ZIG: "${{ steps.zig.outputs.needed }}"
        shell: bash
        run: |
          if [[ "${ZIG}" == 'true' ]]
          then
            [[ "${PAYLOAD_HASH}" == "$(zig fetch "${URL}")" ]]
          else
            [[ -z "${PAYLOAD_HASH}" ]]
          fi
