name: dump

on:
  repository_dispatch:
    types:
      - ping-toolbox
      - ping-vulkan.zig
      - ping-wayland.zig
      - ping-X11.zig
      - ping-glfw.zig
      - ping-cimgui.zig
      - ping-spirv.zig
      - ping-glslang.zig
      - ping-shaderc.zig
      - ping-spaceporn
      - ping-spaceporn-dep-action-env
      - ping-spaceporn-dep-action-bot
      - ping-spaceporn-dep-action-ci
      - ping-spaceporn-dep-action-cd-ping
      - ping-spaceporn-dep-action-cd-pong

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump client_payload
        env:
          CLIENT_PAYLOAD: "${{ toJson(github.event.client_payload) }}"
        run: |
          printf '%s\n' "${CLIENT_PAYLOAD}"

      - name: Check client payload tag field and repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ github.event.client_payload.dependency }}"
          ref: "${{ github.event.client_payload.tag }}"

      - name: Does it needs zig ?
        shell: bash
        run: |
          if [[ -f "${GITHUB_WORKSPACE}/build.zig" ]]
          then
            printf 'zig=true\n' >> "${GITHUB_ENV}"
          else
            printf 'zig=false\n' >> "${GITHUB_ENV}"
          fi

      - uses: goto-bus-stop/setup-zig@v2.2.0
        if: env.zig == 'true'

      - name: Check client payload hash field
        env:
          ZIG: "${{ env.zig }}"
          PAYLOAD_HASH: "${{ github.event.client_payload.hash }}"
        shell: bash
        run: |
          if [[ "${ZIG}" == 'true' ]]
          then
            [[ "${PAYLOAD_HASH}" == "$(zig fetch "${GITHUB_WORKFLOW}")" ]]
          else
            [[ -z "${PAYLOAD_HASH}" ]]
          fi
